### ISSUE TITLE
chalice-local doesn't work

### ISSUE THREAD

**Issue by ghost** [localstack/chalice-local#3]
Since it's the first ticket, I think "doesn't work" sums it up? :)

```
$ chalice-local deploy
Creating deployment package.
Creating IAM role: Maggie-dev
Traceback (most recent call last):
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/chalice-1.22.1-py3.8.egg/chalice/deploy/deployer.py", line 376, in deploy
    return self._deploy(config, chalice_stage_name)
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/chalice-1.22.1-py3.8.egg/chalice/deploy/deployer.py", line 392, in _deploy
    self._executor.execute(plan)
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/chalice-1.22.1-py3.8.egg/chalice/deploy/executor.py", line 42, in execute
    getattr(self, '_do_%s' % instruction.__class__.__name__.lower(),
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/chalice-1.22.1-py3.8.egg/chalice/deploy/executor.py", line 55, in _do_apicall
    result = method(**final_kwargs)
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/chalice-1.22.1-py3.8.egg/chalice/awsclient.py", line 1022, in create_role
    raise e
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/chalice-1.22.1-py3.8.egg/chalice/awsclient.py", line 1018, in create_role
    self.put_role_policy(role_name=name, policy_name=name,
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/chalice-1.22.1-py3.8.egg/chalice/awsclient.py", line 1004, in put_role_policy
    self._client('iam').put_role_policy(
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/botocore-1.20.7-py3.8.egg/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/botocore-1.20.7-py3.8.egg/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.MalformedPolicyDocumentException: An error occurred (MalformedPolicyDocument) when calling the PutRolePolicy operation: Partition "*" is not valid for resource "arn:*:logs:*:*:*".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/chalice-1.22.1-py3.8.egg/chalice/cli/__init__.py", line 636, in main
    return cli(obj={})
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/chalice-1.22.1-py3.8.egg/chalice/cli/__init__.py", line 189, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "/home/mingus/anaconda3/lib/python3.8/site-packages/chalice-1.22.1-py3.8.egg/chalice/deploy/deployer.py", line 378, in deploy
    raise ChaliceDeploymentError(e)
chalice.deploy.deployer.ChaliceDeploymentError: ERROR - While deploying your chalice application, received the following error:

 An error occurred (MalformedPolicyDocument) when calling the PutRolePolicy
 operation: Partition "*" is not valid for resource "arn:*:logs:*:*:*".
```

**Comment by whummer** [comment]
Thanks for reporting @brianmingus2 , and apologies for the long delay. We've been able to reproduce this issue, and it should be fixed in the meantime. Can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks!
